# Generated by Django 5.0.14 on 2025-06-03 20:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VaiTro',
            fields=[
                ('IDVaiTro', models.AutoField(primary_key=True, serialize=False)),
                ('TenVaiTro', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'VAITRO',
            },
        ),
        migrations.CreateModel(
            name='TaiKhoan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ho', models.CharField(max_length=50)),
                ('Ten', models.CharField(max_length=50)),
                ('GioiTinh', models.CharField(max_length=10)),
                ('NgaySinh', models.DateField()),
                ('DiaChi', models.CharField(max_length=255)),
                ('SoDienThoai', models.CharField(max_length=20)),
                ('Email', models.EmailField(max_length=254)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('IDVaiTro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.vaitro')),
            ],
            options={
                'db_table': 'TAIKHOAN',
            },
        ),
    ]
