# Generated by Django 5.0.14 on 2025-07-05 03:09

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VaiTro',
            fields=[
                ('MaVaiTro', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('TenVaiTro', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'VAITRO',
            },
        ),
        migrations.CreateModel(
            name='TaiKhoan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ho', models.CharField(max_length=50)),
                ('Ten', models.CharField(max_length=50)),
                ('GioiTinh', models.CharField(choices=[('Nam', 'Nam'), ('Nữ', 'Nữ'), ('Khác', 'Khác')], max_length=10)),
                ('NgaySinh', models.DateField()),
                ('DiaChi', models.CharField(max_length=255)),
                ('SoDienThoai', models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator('^\\d{10,11}$', 'Số điện thoại không hợp lệ')])),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='taikhoan', to=settings.AUTH_USER_MODEL)),
                ('MaVaiTro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.vaitro')),
            ],
            options={
                'db_table': 'TAIKHOAN',
            },
        ),
    ]
