# Generated by Django 5.0.14 on 2025-07-04 06:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('configurations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HocSinh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ho', models.CharField(max_length=50)),
                ('Ten', models.CharField(max_length=50)),
                ('GioiTinh', models.CharField(max_length=10)),
                ('NgaySinh', models.DateField()),
                ('DiaChi', models.CharField(max_length=255)),
                ('Email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('IDNienKhoaTiepNhan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='configurations.nienkhoa')),
            ],
            options={
                'db_table': 'HOCSINH',
            },
        ),
    ]
