# Generated by Django 5.0.14 on 2025-07-05 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_hocsinh_lophoc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hocsinh',
            name='LopHoc',
        ),
    ]
