# Generated by Django 5.0.14 on 2025-06-12 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('configurations', '0002_thamso_somonhoctoida'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToHop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TenToHop', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'TOHOP',
            },
        ),
        migrations.CreateModel(
            name='MonHoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TenMonHoc', models.CharField(max_length=100)),
                ('IDNienKhoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configurations.nienkhoa')),
                ('IDToHop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='subjects.tohop')),
            ],
            options={
                'db_table': 'MONHOC',
                'unique_together': {('TenMonHoc', 'IDNienKhoa')},
            },
        ),
    ]
