# Generated by Django 5.0.14 on 2025-06-12 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0001_initial'),
        ('students', '0001_initial'),
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HocKy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TenHocKy', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'HOCKY',
            },
        ),
        migrations.CreateModel(
            name='DiemSo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Diem15', models.FloatField(blank=True, null=True)),
                ('Diem1Tiet', models.FloatField(blank=True, null=True)),
                ('DiemTB', models.FloatField(blank=True, null=True)),
                ('IDHocSinh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.hocsinh')),
                ('IDLopHoc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classes.lophoc')),
                ('IDMonHoc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subjects.monhoc')),
                ('IDHocKy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='grading.hocky')),
            ],
            options={
                'db_table': 'DIEMSO',
            },
        ),
    ]
