# Generated by Django 5.0.14 on 2025-07-04 06:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0001_initial'),
        ('students', '0001_initial'),
        ('subjects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HocKy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TenHocKy', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'HOCKY',
            },
        ),
        migrations.CreateModel(
            name='DiemSo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DiemMieng', models.FloatField(blank=True, null=True)),
                ('Diem15Phut', models.FloatField(blank=True, null=True)),
                ('Diem1Tiet', models.FloatField(blank=True, null=True)),
                ('DiemHocKy', models.FloatField(blank=True, null=True)),
                ('DiemTB', models.FloatField(blank=True, null=True)),
                ('NgayCapNhat', models.DateTimeField(auto_now=True)),
                ('IDHocSinh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.hocsinh')),
                ('IDLopHoc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classes.lophoc')),
                ('IDMonHoc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subjects.monhoc')),
                ('NguoiCapNhat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('IDHocKy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='grading.hocky')),
            ],
            options={
                'db_table': 'DIEMSO',
                'unique_together': {('IDHocSinh', 'IDMonHoc', 'IDHocKy')},
            },
        ),
        migrations.CreateModel(
            name='DiemSoLichSu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ThoiGian', models.DateTimeField(auto_now_add=True)),
                ('NoiDungThayDoi', models.TextField()),
                ('DiemGoc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grading.diemso')),
                ('NguoiThayDoi', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'DIEMSO_LICHSU',
            },
        ),
        migrations.CreateModel(
            name='TongKetHocKy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DiemTBHocKy', models.FloatField(blank=True, null=True)),
                ('HocLuc', models.CharField(max_length=20)),
                ('IDHocKy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grading.hocky')),
                ('IDHocSinh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.hocsinh')),
                ('IDLopHoc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classes.lophoc')),
            ],
            options={
                'db_table': 'TONGKET_HOCKY',
                'unique_together': {('IDHocSinh', 'IDLopHoc', 'IDHocKy')},
            },
        ),
    ]
