# Generated by Django 5.0.14 on 2025-07-03 09:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
        ('grading', '0002_diemso_diemmieng_diemso_diemthi_diemso_ngaycapnhat_and_more'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TongKetHocKy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DiemTBHocKy', models.FloatField(blank=True, null=True)),
                ('HocLuc', models.CharField(max_length=20)),
                ('IDHocKy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grading.hocky')),
                ('IDHocSinh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.hocsinh')),
                ('IDLopHoc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classes.lophoc')),
            ],
            options={
                'db_table': 'TONGKET_HOCKY',
                'unique_together': {('IDHocSinh', 'IDLopHoc', 'IDHocKy')},
            },
        ),
    ]
