# Generated by Django 5.0.14 on 2025-07-04 06:17

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NienKhoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TenNienKhoa', models.CharField(help_text='Định dạng YYYY-YYYY, ví dụ: 2023-2024', max_length=9, unique=True)),
            ],
            options={
                'db_table': 'NIENKHOA',
                'ordering': ['-TenNienKhoa'],
            },
        ),
        migrations.CreateModel(
            name='ThamSo',
            fields=[
                ('IDNienKhoa', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, related_name='thamso', serialize=False, to='configurations.nienkhoa')),
                ('TuoiToiThieu', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('TuoiToiDa', models.PositiveIntegerField()),
                ('SoMonHocToiDa', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('SiSoToiDa', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('DiemDatMon', models.FloatField(default=5.0)),
                ('SoLopK10', models.PositiveIntegerField(default=0)),
                ('SoLopK11', models.PositiveIntegerField(default=0)),
                ('SoLopK12', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'THAMSO',
            },
        ),
    ]
