# Generated by Django 5.0.14 on 2025-06-12 17:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='thamso',
            name='SoMonHocToiDa',
            field=models.PositiveIntegerField(default=10, validators=[django.core.validators.MinValueValidator(1)]),
            preserve_default=False,
        ),
    ]
