# Generated by Django 5.0.14 on 2025-06-12 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0002_thamso_somonhoctoida'),
    ]

    operations = [
        migrations.AddField(
            model_name='thamso',
            name='DiemDatMon',
            field=models.FloatField(default=5.0),
        ),
    ]
