# Generated by Django 5.0.14 on 2025-06-12 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0001_initial'),
        ('configurations', '0002_thamso_somonhoctoida'),
        ('grading', '0001_initial'),
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaoCaoHocKy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SiSo', models.IntegerField()),
                ('SoLuongDat', models.IntegerField()),
                ('TiLe', models.FloatField()),
                ('IDHocKy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grading.hocky')),
                ('IDLopHoc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classes.lophoc')),
                ('IDNienKhoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configurations.nienkhoa')),
            ],
            options={
                'db_table': 'BAOCAOHOCKY',
            },
        ),
        migrations.CreateModel(
            name='BaoCaoMonHoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SiSo', models.IntegerField()),
                ('SoLuongDat', models.IntegerField()),
                ('TiLe', models.FloatField()),
                ('IDHocKy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grading.hocky')),
                ('IDLopHoc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classes.lophoc')),
                ('IDMonHoc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subjects.monhoc')),
                ('IDNienKhoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configurations.nienkhoa')),
            ],
            options={
                'db_table': 'BAOCAOMONHOC',
            },
        ),
    ]
