# Generated by Django 5.0.14 on 2025-07-05 03:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('configurations', '0001_initial'),
        ('students', '0001_initial'),
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Khoi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TenKhoi', models.CharField(max_length=10, unique=True)),
            ],
            options={
                'db_table': 'KHOI',
            },
        ),
        migrations.CreateModel(
            name='LopHoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TenLop', models.CharField(max_length=50)),
                ('SiSo', models.PositiveIntegerField(default=0)),
                ('IDKhoi', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='classes.khoi')),
                ('IDNienKhoa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='configurations.nienkhoa')),
                ('IDToHop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='subjects.tohop')),
            ],
            options={
                'db_table': 'LOPHOC',
            },
        ),
        migrations.CreateModel(
            name='LopHoc_HocSinh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IDHocSinh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.hocsinh')),
                ('IDLopHoc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classes.lophoc')),
            ],
            options={
                'db_table': 'LOPHOC_HOCSINH',
                'unique_together': {('IDLopHoc', 'IDHocSinh')},
            },
        ),
        migrations.AddField(
            model_name='lophoc',
            name='HocSinh',
            field=models.ManyToManyField(related_name='lophoc_list', through='classes.LopHoc_HocSinh', to='students.hocsinh'),
        ),
        migrations.CreateModel(
            name='LopHoc_MonHoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IDLopHoc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classes.lophoc')),
                ('IDMonHoc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subjects.monhoc')),
            ],
            options={
                'db_table': 'LOPHOC_MONHOC',
                'unique_together': {('IDLopHoc', 'IDMonHoc')},
            },
        ),
        migrations.AddField(
            model_name='lophoc',
            name='MonHoc',
            field=models.ManyToManyField(related_name='lophoc_list', through='classes.LopHoc_MonHoc', to='subjects.monhoc'),
        ),
        migrations.AlterUniqueTogether(
            name='lophoc',
            unique_together={('TenLop', 'IDNienKhoa')},
        ),
    ]
